// examples/vue/src/App.vue
<script setup>
import { onMounted, ref } from "vue";

const screen = ref(null);
const log = ref("");
const sent = [];

onMounted(async () => {
  const el = screen.value;
  // What screens may do: tool params as JSON Schema (Zod works too).
  el.tools = { "payments.confirm": { type: "object", properties: { amount: { type: "number", exclusiveMinimum: 0 } }, required: ["amount"] } };
  el.components = {
    ProductCard: { description: "A product with its name and price.", positional: ["name"], props: { name: { kind: "text" }, price: { kind: "number" } }, tag: "demo-product-card" },
  };
  el.onMutation = async (call) => {
    sent.push(call.tool);
    // What the person sees: a plain sentence, never the action's raw data.
    log.value = `Paid ${new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(call.params.amount))}. This is a demo: nothing was charged.`;
  };
  el.write(
    [
      "root = Card([title, card, pay])",
      'title = Heading("Confirm payment")',
      'card = ProductCard("Canvas tote", price=24)',
      'pay = Button("Pay now", action="go")',
      'go = McpMutation(pay, tool="payments.confirm", params={amount: 24})',
      "",
    ].join("\n"),
  );
  el.end();

  // ?check: the example checks itself (scripts/examples-test.mjs).
  if (new URLSearchParams(location.search).has("check")) {
    await new Promise((resolve) => setTimeout(resolve, 600));
    const root = el.shadowRoot;
    [...root.querySelectorAll("button")].find((b) => b.textContent.trim() === "Pay now")?.click();
    await new Promise((resolve) => setTimeout(resolve, 300));
    document.getElementById("omni-check").textContent = JSON.stringify({
      framework: "vue",
      drawn: root.textContent.includes("Confirm payment"),
      appComponent: root.querySelector("demo-product-card")?.props?.name === "Canvas tote",
      sent,
    });
  }
});

// Blocked actions and failed handlers: tell the person plainly; the details are for the app's logs.
function onEvent(event) {
  if (event.detail.type === "error") {
    console.warn(event.detail.issue);
    log.value = "That didn't go through. Please try again.";
  }
}
</script>

<template>
  <main style="max-width: 520px; margin: 0 auto; display: grid; gap: 16px">
    <h1>Vue</h1>
    <omni-screen ref="screen" theme="light" @omni-event="onEvent"></omni-screen>
    <p aria-live="polite">{{ log }}</p>
    <pre id="omni-check" hidden></pre>
  </main>
</template>

// examples/svelte/src/App.svelte
<script>
  import { onMount } from "svelte";

  let screen;
  let log = $state("");
  const sent = [];

  onMount(async () => {
    // What screens may do: tool params as JSON Schema (Zod works too).
    screen.tools = { "payments.confirm": { type: "object", properties: { amount: { type: "number", exclusiveMinimum: 0 } }, required: ["amount"] } };
    screen.onMutation = async (call) => {
      sent.push(call.tool);
      // What the person sees: a plain sentence, never the action's raw data.
      log = `Paid ${new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(call.params.amount))}. This is a demo: nothing was charged.`;
    };
    screen.write(
      [
        "root = Card([title, amount, pay])",
        'title = Heading("Confirm payment")',
        "$amount = 24",
        'amount = Text($amount, format="currency", currency="USD", tone="strong")',
        'pay = Button("Pay now", action="go")',
        'go = McpMutation(pay, tool="payments.confirm", params={amount: $amount})',
        "",
      ].join("\n"),
    );
    screen.end();

    // ?check: the example checks itself (scripts/examples-test.mjs).
    if (new URLSearchParams(location.search).has("check")) {
      await new Promise((resolve) => setTimeout(resolve, 600));
      const root = screen.shadowRoot;
      [...root.querySelectorAll("button")].find((b) => b.textContent.trim() === "Pay now")?.click();
      await new Promise((resolve) => setTimeout(resolve, 300));
      document.getElementById("omni-check").textContent = JSON.stringify({
        framework: "svelte",
        drawn: root.textContent.includes("Confirm payment"),
        sent,
      });
    }
  });

  // Blocked actions and failed handlers: tell the person plainly; the details are for the app's logs.
  function onEvent(event) {
    if (event.detail.type === "error") {
      console.warn(event.detail.issue);
      log = "That didn't go through. Please try again.";
    }
  }
</script>

<main style="max-width: 520px; margin: 0 auto; display: grid; gap: 16px">
  <h1>Svelte</h1>
  <omni-screen bind:this={screen} theme="light" onomni-event={onEvent}></omni-screen>
  <p aria-live="polite">{log}</p>
  <pre id="omni-check" hidden></pre>
</main>
